# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean verify
#     - name: Archive Jacoco reports
#       uses: actions/upload-artifact@v3
#       with:
#         name: jacoco-reports
#         path: /home/runner/work/TeamsMessaging/TeamsMessaging/target/site/jacoco

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 80
        min-coverage-changed-files: 80
        title: Code Coverage

    - name: Save Coverage To Environment Variable
      run: |
        echo "TOTAL_COVERAGE=${{ steps.jacoco.outputs.coverage-overall }}" >> $GITHUB_ENV
        echo "CHANGED_FILES_COVERAGE=${{ steps.jacoco.outputs.coverage-changed-files }}" >> $GITHUB_ENV

    - name: Get the Coverage info
      run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}" >> $GITHUB_OUTPUT
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}" >> $GITHUB_OUTPUT

#     - name: Print & Check Coverage Info
#       run: |
#         import os
#         import sys
#         print("Total Coverage: " + str(os.environ["TOTAL_COVERAGE"]))
#         print("Changed Files Coverage: " + str(os.environ["CHANGED_FILES_COVERAGE"]))
#        if float(os.environ["TOTAL_COVERAGE"]) < 80 or float(os.environ["CHANGED_FILES_COVERAGE"]) < 80:
#          print("Insufficient Coverage!")
#          sys.exit(-1) # Cause Status Check Failure due to noncompliant coverage
#        sys.exit(0)
#       shell: python
